domain_status:
  type: entity_table
  description: 'Tabella domini monitorati.'
  fields:
    id:
      type: serial
      unsigned: true
      not null: true
    domain_name:
      type: varchar
      length: 255
      not null: true
    current_status:
      type: varchar
      length: 50
      default: 'unknown'
    alert_enabled:
      type: int
      size: tiny
      default: 0
    alert_mode:
      type: varchar
      length: 20
      default: 'change'
    last_check:
      type: datetime
      not null: true
  primary key: id
  unique keys:
    domain_name: [domain_name]

domain_status_log:
  type: entity_table
  description: 'Log operazioni plugin.'
  fields:
    id:
      type: serial
      unsigned: true
      not null: true
    timestamp:
      type: datetime
      not null: true
    domain_name:
      type: varchar
      length: 255
      not null: true
    message:
      type: text
      not null: true
    log_type:
      type: varchar
      length: 20
      default: 'info'
    source:
      type: varchar
      length: 20
      default: 'cron'
  primary key: id
